[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/STACK:33554432"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-args=-Wl,--stack,33554432"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-z,stack-size=33554432"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-stack_size,0x2000000"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-stack_size,0x2000000"]
